### ISSUE TITLE
洗濯だけアイコンがない

### ISSUE THREAD

**Issue by kkd** [daichancorgi/minchizu#10]
ピッタリのアイコンがないから空白なのかな？
これだけアイコンないので浮きますね。。。

**Comment by daichancorgi** [comment]
さようでございます。
しかも、ライブラリはfontawesome4なのです。

そういえば、マップは"L"と表示されるようにしているんです。
とりあえず、そうしておこうかな。。

**Comment by daichancorgi** [comment]
これもデザイナーさんに手伝ってもらえると、なんとかなる？
