### ISSUE TITLE
地図／マーカーをクリックすると、吹き出しが大きすぎとなることがある

### ISSUE THREAD

**Issue by daichancorgi** [daichancorgi/minchizu#16]
吹き出しが大きすぎて、バツボタンが隠れてしまう。
また、他の情報を見ようと、地図を移動させようとしても、吹き出しが大きすぎて邪魔してしまう。

**Comment by ramu** [comment]
> 吹き出しが大きすぎ

吹き出し( InfoWindow )に固定サイズのスタイル当てれば良さそう。
クラス名だと `.agm-info-window-content` かな。

```
.agm-info-window-content {
  width: 600px;
  height: 250px;
  overflow: scroll;
}
```

**Comment by daichancorgi** [comment]
ありがとうございます〜！
早速、やってみる
