### ISSUE TITLE
登録した被災地情報の状態を切り替えたい

### ISSUE THREAD

**Issue by kkd** [daichancorgi/minchizu#24]
## 概要

現在、吉田町では1000件もの土砂崩れがあり、全貌を誰も把握していない。
重機がこなければ対応できないケースが多く、ボランティアでは対応できない。
重機が入れないような場所もあり、道路の復興後に重機が来るのを待っている状態が多い。
地元の人からすると「うちはまだまだ順番はあとだなぁ」とのんびり構えているそうだ。

とりあえず、みん地図で場所の投稿だけできるようにプロモーションする予定。

ただし、復興した後で、被害地情報が残っているとノイズになるので削除したくなる。
状態を変えて「完了」のようにアクティブと非アクティブを切り替えたい

被災地では**情報鮮度**が重要だと言われた。

## 利用シーン

- 1) 被災者が復興後に削除する
  - ただし忘れそう
- 2) 対応した人が削除する
  - こちらのほうが確度が高そう
- 3) 自治体の人が削除する
  - これが現実的かな。。。

被災者本人がスマホで登録、
自治体の人にみん地図で被害上場所の管理に使ってもらうのがよい気がしている。

## 実現したいこと

- 登録してある情報の状態を変えたい（アクティブ／ノンアクティブがあればいい）
  - 例えばアクティブだと色がついて、ノンアクティブだとグレーになるとか
- 削除だと間違って消しちゃうとまずいので状態切替かな？
- ユーザ権限とかいうと面倒なので、誰でも帰れるようにするほうが現実的？
- 登録した人が変更するとは限らないので、誰でも変更できるようにしたほうがいいかもしれない
  - 悪意のあるユーザーができちゃうけど、それはない前提で今はいいかな？

**Comment by daichancorgi** [comment]
これはやりたいんですよねー。優先度あげてやりますか。
本当は、情報の追記もできるようにしたいんだけど、それはちょっと置いておくか。

自治体とかとの組み合わせ、みん地図は合ってる気がする。

**Comment by daichancorgi** [comment]
ひとまず、mapには赤色文字で文言を入れることにした
