### ISSUE TITLE
地図でマーカーを選択してからグーグルマップが開きたい

### ISSUE THREAD

**Issue by kkd** [daichancorgi/minchizu#63]
今だと、Googleマップに飛ばすには、一覧から情報を選ばないといけない。
地図でマーカーを探す→選択する→Googleマップに飛ばしてナビゲーション、という流れが自然だしやりたくなる。

**Comment by daichancorgi** [comment]
これは、地図でカテゴリのフィルターが欲しいと言う感じでしょうか？
「Googleマップで見る」のリンクは、地図画面でピンをタップして出る吹き出しの中にはあります

**Comment by kkd** [comment]
あ、ありました！気づかなかった。。。closeします。
